[package]
name = "tribles"
version = "0.1.2"
authors = ["Jan Bramkamp <crest@rlwinm.de>", "⚫️ <jp@bultmann.eu>"]
edition = "2018"
description = "The tribles knowledge base implementation for rust."
homepage = "https://tribles.space"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.0.0"
rand = "0.8.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false