[package]
name = "tribles"
version = "0.2.0-alpha-1"
authors = ["Jan Bramkamp <crest@rlwinm.de>", "⚫️ <jp@bultmann.eu>", "Vanja Sophie Cangalovic <vanja@bultmann.eu>"]
edition = "2018"
description = "The tribles knowledge base implementation for rust."
homepage = "https://tribles.space"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = { version = "15.1.0", features = ["pool"] }
rand = "0.8.3"

[dev-dependencies]
criterion = "0.3"
proptest = "1.0.0"

[[bench]]
name = "benchmark"
harness = false

[profile.bench]
opt-level = 3