[package]
name = "tribles"
version = "0.2.0-alpha-1"
authors = ["Jan Bramkamp <crest@rlwinm.de>", "⚫️ <jp@bultmann.eu>", "Vanja Sophie Cangalovic <vanja@bultmann.eu>"]
edition = "2018"
description = "The tribles knowledge base implementation for rust."
homepage = "https://tribles.space"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
triomphe = "0.1.8"
rand = "0.8.5"
ux = "0.1.5"
siphasher = "0.3"
arbitrary = { version = "1", features = ["derive"] }
cardkit = "0.1.0-alpha.10"

#[dev-dependencies]
criterion = "0.3"
proptest = "1.0"
im = "15.1.0"
itertools = "0.10.5"
peak_alloc = "0.1.0"

[[bench]]
name = "benchmark"
harness = false

[profile.bench]
opt-level = 3
