[package]
name = "tribles"
version = "0.1.2"
authors = ["Jan Bramkamp <crest@rlwinm.de>", "⚫️ <jp@bultmann.eu>"]
edition = "2018"
description = "The tribles knowledge base implementation for rust."
homepage = "https://tribles.space"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
im = "15.0.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false