name: Preflight

on:
  push:
    branches: [main]
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Run preflight script
        uses: model-checking/kani-github-action@v1
        with:
          command: ./scripts/preflight.sh
